# Use the latest Node.js image as the base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /app

# Copy all files from the current directory to the container's working directory
COPY . .

# Install Node.js dependencies
RUN npm install

# Expose port 3001 for the application
EXPOSE 3001
